name: products_general_machine_system_services_android
description: A Library Full Package Template
version: 0.0.0
homepage: https://github.com/azkadev/products_general_machine_system_services
repository: https://github.com/azkadev/products_general_machine_system_services
issue_tracker: https://github.com/azkadev/products_general_machine_system_services/issues 
documentation: https://youtube.com/@azkadev
funding:
  - https://github.com/sponsors/azkadev


platforms:
 android:
 ios:
 linux:
 macos:
 web:
 windows:

# topics:
#   - products_general_machine_system_services
#   - products_general_machine_system_services_flutter
#   - products_general_machine_system_services_dart

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
 